spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/animais}
    driver-class-name: org.postgresql.Driver
    username: usuario
    password: 87654321
    sqlScriptEncoding: UTF-8
    initialization-mode: always
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
  application:
    name: gerenciamento-animais-ms

eureka:
  instance:
    hostname: localhost
    instance-id: ${spring.application.name}:${random.value}
  client:
    serviceUrl:
      defaultZone: http://localhost:8082/eureka

server:
  port: 0

